waitUntil {!isNull findDisplay 46 && !isNil 'ExileClientLoadedIn' && getPlayerUID player != ''};
uiSleep 0.1;	
if !(isClass (configFile >> "CfgPatches" >> "maa_Uniform")) then {["Requires MOD Tryk 0.9.5 Fix!"] spawn BIS_fnc_guiMessage;};
if !(isClass (configFile >> "CfgPatches" >> "CUP_Chernarus_Data")) then {["Requires MOD CUP Terrains!"] spawn BIS_fnc_guiMessage};
if !(isClass (configFile >> "CfgPatches" >> "Ryanzombies")) then {["Requires MOD Ryan Zombies!"] spawn BIS_fnc_guiMessage};
if !(isClass (configFile >> "CfgPatches" >> "hlcweapons_core")) then {["Requires MOD NiArsenal!"] spawn BIS_fnc_guiMessage};
//[] execVM "statusIcons\statusIcons.sqf";
player addAction ["Teleport", "openMap true;onMapSingleClick 'player setPos _pos; onMapSingleClick ''''; openMap false; true;'; waitUntil{!(visibleMap)}; "];
[] execVM "Client_scriptsAndFunctions\initClient.sqf";
_bul = [] execVM "addons\blowout\module\blowout_client.sqf";